"""Add email column to User table

Revision ID: 249e98a88974
Revises: 7a49bc06778d
Create Date: 2025-05-04 16:20:30.390046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249e98a88974'
down_revision = '7a49bc06778d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option_2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option_3', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option_4', sa.String(length=100), nullable=False))
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('text')
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_a')
        batch_op.drop_column('category')
        batch_op.drop_column('option_c')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_c', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('option_a', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_d', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_b', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=500), nullable=False))
        batch_op.alter_column('correct_option',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.drop_column('option_4')
        batch_op.drop_column('option_3')
        batch_op.drop_column('option_2')
        batch_op.drop_column('option_1')
        batch_op.drop_column('question_text')

    # ### end Alembic commands ###
